# Generated by Django 2.1.1 on 2018-10-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181007_0901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPurchageManager',
        ),
    ]
